# Python Lab Assignment — German Credit Analysis




**Datasets required:**
- `German-Credit_1.csv`
- `German-Credit_2.csv`




In [ ]:
# Import required libraries
import pandas as pd
import numpy as np

print("Libraries imported successfully.")


Libraries imported successfully.


## Step 0 — Upload the two datasets

Run the cell below and upload **both** `German-Credit_1.csv` and `German-Credit_2.csv`.


In [ ]:
# Upload the two CSV files in Google Colab
from google.colab import files
import os

required_files = ["German-Credit_1.csv", "German-Credit_2.csv"]
missing_files = [f for f in required_files if not os.path.exists(f)]

if missing_files:
    print("Please upload both CSV files.")
    uploaded = files.upload()
else:
    print("Both CSV files are already available. No upload needed.")

for filename in required_files:
    if not os.path.exists(filename):
        raise FileNotFoundError(
            f"{filename} was not found. Please run this cell again and upload the required CSV files."
        )

print("\nDataset files ready:")
for filename in required_files:
    print("-", filename)


Both CSV files are already available. No upload needed.

Dataset files ready:
- German-Credit_1.csv
- German-Credit_2.csv


# (a) Data Loading & Understanding

### (a) Load both datasets and display the first 5 rows


In [ ]:
# Load both datasets
df1 = pd.read_csv("German-Credit_1.csv")
df2 = pd.read_csv("German-Credit_2.csv")

print("German-Credit_1.csv — First 5 Rows")
display(df1.head())

print("\nGerman-Credit_2.csv — First 5 Rows")
display(df2.head())


German-Credit_1.csv — First 5 Rows


,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,PROP_UNKN_NONE,AGE,OTHER_INSTALL,RENT,OWN_RES,NUM_CREDITS,NUM_DEPENDENTS,TELEPHONE,FOREIGN,RESPONSE
0,1,6.0,0.0,0.0,0.0,1.0,0.0,0.0,1169.0,4.0,...,0.0,67.0,0.0,0.0,1.0,2.0,1.0,1.0,0.0,1.0
1,2,48.0,0.0,0.0,0.0,1.0,0.0,0.0,5951.0,2.0,...,0.0,22.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
2,3,12.0,0.0,0.0,0.0,0.0,1.0,0.0,2096.0,2.0,...,0.0,49.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,1.0
3,4,42.0,0.0,0.0,1.0,0.0,0.0,0.0,7882.0,2.0,...,0.0,45.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0
4,5,24.0,1.0,0.0,0.0,0.0,0.0,0.0,4870.0,3.0,...,1.0,53.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0



German-Credit_2.csv — First 5 Rows


,OBS,CHK_ACCT,HISTORY,SAV_ACCT,EMPLOYMENT,PRESENT_RESIDENT,JOB
0,1,0,4,4,4,4,2
1,2,1,2,0,2,2,2
2,3,3,4,0,3,3,1
3,4,0,2,0,3,4,2
4,5,0,3,0,2,4,2


### (b) Check the shape of both datasets


In [ ]:
print("Shape of German-Credit_1:", df1.shape)
print("Shape of German-Credit_2:", df2.shape)


Shape of German-Credit_1: (1000, 23)
Shape of German-Credit_2: (1000, 7)


### (c) Display column names and identify numerical features


In [ ]:
print("Columns in German-Credit_1:")
print(df1.columns.tolist())

print("\nColumns in German-Credit_2:")
print(df2.columns.tolist())

numerical_features_df1 = df1.select_dtypes(include=np.number).columns.tolist()
numerical_features_df2 = df2.select_dtypes(include=np.number).columns.tolist()

print("\nNumerical features in German-Credit_1:")
print(numerical_features_df1)

print("\nNumerical features in German-Credit_2:")
print(numerical_features_df2)


Columns in German-Credit_1:
['OBS', 'DURATION', 'NEW_CAR', 'USED_CAR', 'FURNITURE', 'RADIO_TV', 'EDUCATION', 'RETRAINING', 'AMOUNT', 'INSTALL_RATE', 'CO_APPLICANT', 'GUARANTOR', 'REAL_ESTATE', 'PROP_UNKN_NONE', 'AGE', 'OTHER_INSTALL', 'RENT', 'OWN_RES', 'NUM_CREDITS', 'NUM_DEPENDENTS', 'TELEPHONE', 'FOREIGN', 'RESPONSE']

Columns in German-Credit_2:
['OBS', 'CHK_ACCT', 'HISTORY', 'SAV_ACCT', 'EMPLOYMENT', 'PRESENT_RESIDENT', 'JOB']

Numerical features in German-Credit_1:
['OBS', 'DURATION', 'NEW_CAR', 'USED_CAR', 'FURNITURE', 'RADIO_TV', 'EDUCATION', 'RETRAINING', 'AMOUNT', 'INSTALL_RATE', 'CO_APPLICANT', 'GUARANTOR', 'REAL_ESTATE', 'PROP_UNKN_NONE', 'AGE', 'OTHER_INSTALL', 'RENT', 'OWN_RES', 'NUM_CREDITS', 'NUM_DEPENDENTS', 'TELEPHONE', 'FOREIGN', 'RESPONSE']

Numerical features in German-Credit_2:
['OBS', 'CHK_ACCT', 'HISTORY', 'SAV_ACCT', 'EMPLOYMENT', 'PRESENT_RESIDENT', 'JOB']


### (d) Use `info()` to check missing values

`info()` shows the number of non-null values and data types. A missing-value count is also displayed below for clarity.


In [ ]:
print("Information for German-Credit_1:")
df1.info()

print("\nMissing values in German-Credit_1:")
display(df1.isnull().sum().to_frame("Missing Values"))

print("\nInformation for German-Credit_2:")
df2.info()

print("\nMissing values in German-Credit_2:")
display(df2.isnull().sum().to_frame("Missing Values"))


Information for German-Credit_1:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   OBS             1000 non-null   int64  
 1   DURATION        998 non-null    float64
 2   NEW_CAR         999 non-null    float64
 3   USED_CAR        999 non-null    float64
 4   FURNITURE       999 non-null    float64
 5   RADIO_TV        997 non-null    float64
 6   EDUCATION       996 non-null    float64
 7   RETRAINING      996 non-null    float64
 8   AMOUNT          990 non-null    float64
 9   INSTALL_RATE    993 non-null    float64
 10  CO_APPLICANT    992 non-null    float64
 11  GUARANTOR       993 non-null    float64
 12  REAL_ESTATE     993 non-null    float64
 13  PROP_UNKN_NONE  993 non-null    float64
 14  AGE             990 non-null    float64
 15  OTHER_INSTALL   991 non-null    float64
 16  RENT            992 non-null    float64
 17  O

,Missing Values
OBS,0
DURATION,2
NEW_CAR,1
USED_CAR,1
FURNITURE,1
RADIO_TV,3
EDUCATION,4
RETRAINING,4
AMOUNT,10
INSTALL_RATE,7



Information for German-Credit_2:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OBS               1000 non-null   int64
 1   CHK_ACCT          1000 non-null   int64
 2   HISTORY           1000 non-null   int64
 3   SAV_ACCT          1000 non-null   int64
 4   EMPLOYMENT        1000 non-null   int64
 5   PRESENT_RESIDENT  1000 non-null   int64
 6   JOB               1000 non-null   int64
dtypes: int64(7)
memory usage: 54.8 KB

Missing values in German-Credit_2:


,Missing Values
OBS,0
CHK_ACCT,0
HISTORY,0
SAV_ACCT,0
EMPLOYMENT,0
PRESENT_RESIDENT,0
JOB,0


# (b) Data Exploration

### (a) Find the average credit amount (`AMOUNT`)


In [ ]:
average_amount = df1["AMOUNT"].mean()
print(f"Average credit amount (AMOUNT): {average_amount:.2f}")


Average credit amount (AMOUNT): 3273.17


### (b) Find the maximum and minimum `AGE`


In [ ]:
maximum_age = df1["AGE"].max()
minimum_age = df1["AGE"].min()

print(f"Maximum AGE: {maximum_age:.0f}")
print(f"Minimum AGE: {minimum_age:.0f}")


Maximum AGE: 75
Minimum AGE: 19


### (c) Count customers with `RESPONSE = 1`


In [ ]:
response_1_count = (df1["RESPONSE"] == 1).sum()
print(f"Number of customers with RESPONSE = 1: {response_1_count}")


Number of customers with RESPONSE = 1: 698


### (d) Find the distribution of `INSTALL_RATE`


In [ ]:
install_rate_distribution = df1["INSTALL_RATE"].value_counts().sort_index()

print("Distribution of INSTALL_RATE:")
display(install_rate_distribution.to_frame("Count"))


Distribution of INSTALL_RATE:


,Count
INSTALL_RATE,
1.0,135
2.0,230
3.0,155
4.0,473


# (c) Data Manipulation

### (a) Create a new column: `AMOUNT_PER_DURATION`


In [ ]:
# Create the new column
df1["AMOUNT_PER_DURATION"] = df1["AMOUNT"] / df1["DURATION"]

print("First 5 rows showing the new column:")
display(df1[["AMOUNT", "DURATION", "AMOUNT_PER_DURATION"]].head())


First 5 rows showing the new column:


,AMOUNT,DURATION,AMOUNT_PER_DURATION
0,1169.0,6.0,194.833333
1,5951.0,48.0,123.979167
2,2096.0,12.0,174.666667
3,7882.0,42.0,187.666667
4,4870.0,24.0,202.916667


### (b) Filter customers with `AGE > 40` and `AMOUNT > 5000`


In [ ]:
filtered_customers = df1[(df1["AGE"] > 40) & (df1["AMOUNT"] > 5000)]

print(f"Number of customers matching AGE > 40 and AMOUNT > 5000: {len(filtered_customers)}")
display(filtered_customers.head(10))


Number of customers matching AGE > 40 and AMOUNT > 5000: 60


,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,AGE,OTHER_INSTALL,RENT,OWN_RES,NUM_CREDITS,NUM_DEPENDENTS,TELEPHONE,FOREIGN,RESPONSE,AMOUNT_PER_DURATION
3,4,42.0,0.0,0.0,1.0,0.0,0.0,0.0,7882.0,2.0,...,45.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0,187.666667
18,19,24.0,0.0,1.0,0.0,0.0,0.0,0.0,12579.0,4.0,...,44.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,524.125000
29,30,60.0,0.0,0.0,0.0,0.0,0.0,1.0,6836.0,3.0,...,63.0,0.0,0.0,1.0,2.0,1.0,1.0,0.0,0.0,113.933333
42,43,18.0,0.0,0.0,0.0,0.0,0.0,0.0,6204.0,2.0,...,44.0,0.0,0.0,1.0,1.0,2.0,1.0,0.0,1.0,344.666667
44,45,48.0,0.0,1.0,0.0,0.0,0.0,0.0,6143.0,4.0,...,58.0,1.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,127.979167
56,57,12.0,0.0,0.0,0.0,1.0,0.0,0.0,6468.0,2.0,...,52.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,539.000000
65,66,27.0,0.0,0.0,0.0,0.0,0.0,0.0,5190.0,4.0,...,48.0,0.0,0.0,1.0,4.0,2.0,1.0,0.0,1.0,192.222222
73,74,42.0,0.0,0.0,0.0,0.0,0.0,1.0,5954.0,2.0,...,41.0,1.0,0.0,1.0,2.0,1.0,0.0,0.0,1.0,141.761905
80,81,24.0,0.0,0.0,0.0,1.0,0.0,0.0,5943.0,1.0,...,44.0,0.0,0.0,1.0,2.0,1.0,1.0,0.0,0.0,247.625000
87,88,36.0,0.0,0.0,0.0,0.0,1.0,0.0,12612.0,1.0,...,47.0,0.0,0.0,0.0,1.0,2.0,1.0,0.0,0.0,350.333333


### (c) Sort data based on `AMOUNT` in descending order


In [ ]:
sorted_by_amount = df1.sort_values(by="AMOUNT", ascending=False)

print("Top 10 customers sorted by AMOUNT (descending):")
display(sorted_by_amount[["OBS", "AMOUNT", "DURATION", "AGE", "RESPONSE"]].head(10))


Top 10 customers sorted by AMOUNT (descending):


,OBS,AMOUNT,DURATION,AGE,RESPONSE
915,916,18424.0,48.0,32.0,0.0
95,96,15945.0,54.0,58.0,0.0
818,819,15857.0,36.0,43.0,1.0
887,888,15672.0,48.0,23.0,0.0
637,638,15653.0,60.0,21.0,1.0
917,918,14896.0,6.0,68.0,0.0
374,375,14782.0,60.0,60.0,0.0
236,237,14555.0,6.0,23.0,0.0
63,64,14421.0,48.0,25.0,0.0
378,379,14318.0,36.0,57.0,0.0


# (d) Grouping & Analysis

### (a) Group by `RESPONSE` and find mean `AMOUNT`


In [ ]:
mean_amount_by_response = df1.groupby("RESPONSE")["AMOUNT"].mean()

print("Mean AMOUNT for each RESPONSE:")
display(mean_amount_by_response.to_frame("Mean AMOUNT"))


Mean AMOUNT for each RESPONSE:


,Mean AMOUNT
RESPONSE,
0.0,3946.831081
1.0,2986.940837


### (b) Find average `AGE` for each `RESPONSE`


In [ ]:
average_age_by_response = df1.groupby("RESPONSE")["AGE"].mean()

print("Average AGE for each RESPONSE:")
display(average_age_by_response.to_frame("Average AGE"))


Average AGE for each RESPONSE:


,Average AGE
RESPONSE,
0.0,33.787162
1.0,36.207792


# (e) Merging & Advanced

### (a) Merge both datasets using the `OBS` column


In [ ]:
# Merge the two datasets using the common OBS column
merged_df = pd.merge(df1, df2, on="OBS", how="inner")

print("Shape of merged dataset:", merged_df.shape)
print("\nFirst 5 rows of merged dataset:")
display(merged_df.head())


Shape of merged dataset: (1000, 30)

First 5 rows of merged dataset:


,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,TELEPHONE,FOREIGN,RESPONSE,AMOUNT_PER_DURATION,CHK_ACCT,HISTORY,SAV_ACCT,EMPLOYMENT,PRESENT_RESIDENT,JOB
0,1,6.0,0.0,0.0,0.0,1.0,0.0,0.0,1169.0,4.0,...,1.0,0.0,1.0,194.833333,0,4,4,4,4,2
1,2,48.0,0.0,0.0,0.0,1.0,0.0,0.0,5951.0,2.0,...,0.0,0.0,0.0,123.979167,1,2,0,2,2,2
2,3,12.0,0.0,0.0,0.0,0.0,1.0,0.0,2096.0,2.0,...,0.0,0.0,1.0,174.666667,3,4,0,3,3,1
3,4,42.0,0.0,0.0,1.0,0.0,0.0,0.0,7882.0,2.0,...,0.0,0.0,1.0,187.666667,0,2,0,3,4,2
4,5,24.0,1.0,0.0,0.0,0.0,0.0,0.0,4870.0,3.0,...,0.0,0.0,0.0,202.916667,0,3,0,2,4,2


### (b) Find correlation between numerical variables


In [ ]:
# Calculate correlation between all numerical variables
numerical_merged = merged_df.select_dtypes(include=np.number)
correlation_matrix = numerical_merged.corr()

print("Correlation matrix:")
display(correlation_matrix.round(2))


Correlation matrix:


,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,TELEPHONE,FOREIGN,RESPONSE,AMOUNT_PER_DURATION,CHK_ACCT,HISTORY,SAV_ACCT,EMPLOYMENT,PRESENT_RESIDENT,JOB
OBS,1.00,0.03,0.06,0.01,-0.01,-0.02,-0.02,-0.02,0.01,0.01,...,0.00,-0.02,-0.04,-0.01,0.01,-0.01,0.00,-0.02,0.02,-0.03
DURATION,0.03,1.00,-0.11,0.15,-0.06,-0.04,0.00,0.16,0.62,0.07,...,0.17,-0.14,-0.21,-0.13,-0.07,-0.08,0.05,0.06,0.03,0.21
NEW_CAR,0.06,-0.11,1.00,-0.19,-0.26,-0.35,-0.13,-0.18,-0.04,-0.05,...,-0.04,0.16,-0.10,0.11,-0.07,0.04,-0.00,-0.02,0.02,-0.09
USED_CAR,0.01,0.15,-0.19,1.00,-0.16,-0.21,-0.08,-0.11,0.26,-0.09,...,0.13,-0.03,0.10,0.11,0.06,0.04,0.11,0.04,0.11,0.18
FURNITURE,-0.01,-0.06,-0.26,-0.16,1.00,-0.29,-0.11,-0.15,-0.04,-0.06,...,-0.05,-0.01,-0.02,0.01,-0.10,-0.02,-0.08,-0.08,-0.01,0.02
RADIO_TV,-0.02,-0.04,-0.35,-0.21,-0.29,1.00,-0.14,-0.20,-0.17,0.14,...,-0.08,-0.06,0.11,-0.13,0.11,0.02,-0.00,0.08,-0.09,-0.03
EDUCATION,-0.02,0.00,-0.13,-0.08,-0.11,-0.14,1.00,-0.08,-0.01,0.04,...,0.02,-0.05,-0.07,-0.03,0.01,0.05,0.01,0.02,0.04,-0.00
RETRAINING,-0.02,0.16,-0.18,-0.11,-0.15,-0.20,-0.08,1.00,0.10,-0.03,...,0.09,-0.05,-0.04,-0.03,0.02,-0.09,-0.02,0.02,-0.05,0.00
AMOUNT,0.01,0.62,-0.04,0.26,-0.04,-0.17,-0.01,0.10,1.00,-0.27,...,0.28,-0.05,-0.16,0.52,-0.04,-0.07,0.06,-0.01,0.03,0.28
INSTALL_RATE,0.01,0.07,-0.05,-0.09,-0.06,0.14,0.04,-0.03,-0.27,1.00,...,0.02,-0.09,-0.07,-0.40,-0.01,0.04,0.02,0.12,0.04,0.09


# (f) NumPy Tasks

### (a) Create a 3×4 NumPy array and print shape, size, and dtype


In [ ]:
array_3x4 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("3×4 array:")
print(array_3x4)
print("\nShape:", array_3x4.shape)
print("Size:", array_3x4.size)
print("Data type:", array_3x4.dtype)


3×4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape: (3, 4)
Size: 12
Data type: int64


### (b) Create arrays using `zeros()`, `ones()`, and `full()`


In [ ]:
zeros_array = np.zeros((2, 3))
ones_array = np.ones((2, 3))
full_array = np.full((2, 3), 7)

print("zeros():")
print(zeros_array)

print("\nones():")
print(ones_array)

print("\nfull() with value 7:")
print(full_array)


zeros():
[[0. 0. 0.]
 [0. 0. 0.]]

ones():
[[1. 1. 1.]
 [1. 1. 1.]]

full() with value 7:
[[7 7 7]
 [7 7 7]]


### (c) Generate numbers using `arange()` and `linspace()`


In [ ]:
arange_array = np.arange(0, 10, 2)
linspace_array = np.linspace(0, 10, 5)

print("Using arange(0, 10, 2):")
print(arange_array)

print("\nUsing linspace(0, 10, 5):")
print(linspace_array)


Using arange(0, 10, 2):
[0 2 4 6 8]

Using linspace(0, 10, 5):
[ 0.   2.5  5.   7.5 10. ]


### (d) Create a random array and fix randomness using `seed`


In [ ]:
np.random.seed(42)

random_array = np.random.rand(3, 3)

print("Random 3×3 array with seed 42:")
print(random_array)


Random 3×3 array with seed 42:
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


### (e) Perform indexing — first, last, and a specific element


In [ ]:
index_array = np.array([10, 20, 30, 40, 50])

print("Array:", index_array)
print("First element:", index_array[0])
print("Last element:", index_array[-1])
print("Specific element (index 2):", index_array[2])


Array: [10 20 30 40 50]
First element: 10
Last element: 50
Specific element (index 2): 30


### (f) Slice a 2D array to extract a submatrix


In [ ]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

submatrix = matrix[1:3, 1:3]

print("Original matrix:")
print(matrix)

print("\nExtracted submatrix:")
print(submatrix)


Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Extracted submatrix:
[[ 6  7]
 [10 11]]


### (g) Reshape a 1D array into a 2D array


In [ ]:
one_d_array = np.arange(1, 13)
two_d_array = one_d_array.reshape(3, 4)

print("1D array:")
print(one_d_array)

print("\nReshaped 2D array (3×4):")
print(two_d_array)


1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 2D array (3×4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### (h) Perform transpose of a matrix


In [ ]:
print("Original matrix:")
print(two_d_array)

print("\nTransposed matrix:")
print(two_d_array.T)


Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed matrix:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### (i) Demonstrate the difference between `view()` and `copy()`


In [ ]:
original = np.array([1, 2, 3, 4, 5])

view_array = original.view()
copy_array = original.copy()

# Change the view and copy
view_array[0] = 100
copy_array[1] = 200

print("Original array after changing the view and copy:")
print(original)

print("\nView array:")
print(view_array)

print("\nCopy array:")
print(copy_array)

print("\nExplanation:")
print("- The view shares data with the original array, so changing the view changes the original.")
print("- The copy has independent data, so changing the copy does not change the original.")


Original array after changing the view and copy:
[100   2   3   4   5]

View array:
[100   2   3   4   5]

Copy array:
[  1 200   3   4   5]

Explanation:
- The view shares data with the original array, so changing the view changes the original.
- The copy has independent data, so changing the copy does not change the original.


### (j) Reverse an array using slicing


In [ ]:
reverse_array = np.array([1, 2, 3, 4, 5])

print("Original array:", reverse_array)
print("Reversed array:", reverse_array[::-1])


Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]
